import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/reset.css',
                'resources/css/fonts.css',
                'resources/css/colors.css',
                'resources/css/icons.css',
                'resources/css/footer.css',
                'resources/css/header.css',
                'resources/css/auth.css',
                'resources/css/buttons.css',
                'resources/css/library.css',
                'resources/css/inputs.css',
                'resources/css/book.css',
                'resources/css/events.css',
                'resources/css/event.css',
                'resources/css/profile.css',
                'resources/css/litar.css',
                'resources/css/pdf-viewer.css',
                'resources/css/authors-comics-landing.css',
                'resources/css/authors-comics-library.css',
                'resources/css/comic.css',
                'resources/css/home.css',
                'resources/css/news.css',
                'resources/css/verify-email.css',
                'resources/css/player.css',

                'resources/css/editor/dashboard.css',
                'resources/css/editor/create_event.css',
                'resources/css/editor/create_post.css',
                'resources/css/editor/create_catalog.css',
                'resources/css/editor/events_list.css',
                'resources/css/editor/multimedia_list.css',
                'resources/css/editor/catalog_list.css',
                'resources/css/editor/authors_сomics_submissions_list.css',
                'resources/css/editor/authors_comics_moderation.css',

                'resources/css/user/author_comics_list.css',
                'resources/css/user/create_author_comics.css',
                'resources/css/user/moderation-confirm-comics.css',
                'resources/css/user/settings.css',
                'resources/css/manuals.css',

                'resources/js/app.js',
                'resources/js/header.js',
                'resources/js/home.js',
                'resources/js/news.js',
                'resources/js/player.js',
                'resources/js/profile-dropdown.js',
                'resources/js/mobile-menu.js',
                'resources/js/library.js',
                'resources/js/events.js',
                'resources/js/auth-tabs.js',
                'resources/js/toggleSubscription.js',
                'resources/js/event-map.js',
                'resources/js/pdf-viewer.js',
                'resources/js/swiper-slider.js',
                'resources/js/rating.js',
                'resources/js/profile-tabs.js',
                'resources/js/comment.js',
                'resources/js/blob.js',
                'resources/js/dynamic-cover.js',
                'resources/js/moderation-confirm-comics.js',
                'resources/js/comics-list-wrapper-fix.js',
                'resources/js/authors-comics-library.js',
                'resources/js/verify-email.js',
                'resources/js/newsfeed-slider.js',

                'resources/js/editor/multimedia-list-modal.js',
                'resources/js/editor/events-list-modal.js',
                'resources/js/editor/catalog-list-modal.js',
                'resources/js/editor/submissions_items.js',
                'resources/js/editor/catalog_items.js',
                'resources/js/editor/events_items.js',
                'resources/js/editor/multimedia_items.js',

                'resources/js/user/author-comics-list-modal.js',
                'resources/js/user/settings.js',
                'resources/js/user/authors_comics_items.js',
            ],
            refresh: true,
        }),
    ],
});
